[workspace]
members = ["tee"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["LiliumOS Team"]
edition = "2021"

[workspace.dependencies]
lilium-sys = { git = "https://github.com/LiliumOS/lilium-sys" }
